# Generated by Django 5.2.4 on 2025-08-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='avatars/defaultAvatar.png', upload_to='avatars/'),
        ),
    ]
